api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "preorder-and-availability"
type = "function"
uid = "5b63fd93-f6b4-56e9-f199-0e6ccef8429e8a839959"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/preorder_availability.graphql"
  export = "preorder-availability"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
